{
	"document_title": "CVE-2024-39705",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2024-39705"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "2",
				"date": "2024-07-04T23:09:38Z",
				"description": "current"
			}
		},
		"initial_release_date": "2024-06-29T17:04:34Z",
		"current_release_date": "2024-07-04T23:09:38Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2024-39705",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "NLTK through 3.8.1 allows remote code execution if untrusted packages have pickled Python code, and the integrated data package download functionality is used. This affects, for example, averaged_perceptron_tagger and punkt.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python310-nltk-3.8.1-2.1",
				"full_product_name": {
					"text": "python310-nltk-3.8.1-2.1",
					"product_id": "python310-nltk-3.8.1-2.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-nltk-3.8.1-2.1",
				"full_product_name": {
					"text": "python311-nltk-3.8.1-2.1",
					"product_id": "python311-nltk-3.8.1-2.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python312-nltk-3.8.1-2.1",
				"full_product_name": {
					"text": "python312-nltk-3.8.1-2.1",
					"product_id": "python312-nltk-3.8.1-2.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python310-nltk-3.8.1-2.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-nltk-3.8.1-2.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python312-nltk-3.8.1-2.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "NLTK through 3.8.1 allows remote code execution if untrusted packages have pickled Python code, and the integrated data package download functionality is used. This affects, for example, averaged_perceptron_tagger and punkt.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2024-39705",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-nltk-3.8.1-2.1",
						"openSUSE Tumbleweed:python311-nltk-3.8.1-2.1",
						"openSUSE Tumbleweed:python312-nltk-3.8.1-2.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "low"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {},
				"score_set_v_3": {}
			}
		}
	]
}
