{
  "document_title": "CVE-2017-7233",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2017-7233"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "23",
        "date": "2023-03-21T01:41:55Z",
        "description": "current"
      }
    },
    "initial_release_date": "2021-05-30T13:54:19Z",
    "current_release_date": "2023-03-21T01:41:55Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2017-7233",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003895.html",
      "description": "E-Mail link for SUSE-SU-2018:0973-1"
    },
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html",
      "description": "E-Mail link for SUSE-SU-2018:1102-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00024.html",
      "description": "E-Mail link for openSUSE-SU-2018:0632-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00103.html",
      "description": "E-Mail link for openSUSE-SU-2018:0824-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00105.html",
      "description": "E-Mail link for openSUSE-SU-2018:0826-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/OGS4NP24275NERRPQV6A6EONV6W3C2SK/",
      "description": "E-Mail link for openSUSE-SU-2023:0077-1"
    },
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "SUSE OpenStack Cloud 6",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE OpenStack Cloud 6",
            "full_product_name": {
              "text": "SUSE OpenStack Cloud 6",
              "product_id": "SUSE OpenStack Cloud 6",
              "cpe": "cpe:/o:suse:suse-openstack-cloud:6"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "SUSE OpenStack Cloud 7",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE OpenStack Cloud 7",
            "full_product_name": {
              "text": "SUSE OpenStack Cloud 7",
              "product_id": "SUSE OpenStack Cloud 7",
              "cpe": "cpe:/o:suse:suse-openstack-cloud:7"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "SUSE Package Hub 12",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE Package Hub 12",
            "full_product_name": {
              "text": "SUSE Package Hub 12",
              "product_id": "SUSE Package Hub 12",
              "cpe": "cpe:/o:suse:packagehub:12"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "SUSE Package Hub 12 SP1",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE Package Hub 12 SP1",
            "full_product_name": {
              "text": "SUSE Package Hub 12 SP1",
              "product_id": "SUSE Package Hub 12 SP1",
              "cpe": "cpe:/o:suse:packagehub:12:sp1"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "openSUSE Tumbleweed",
        "branch": [
          {
            "type": "Product Name",
            "name": "openSUSE Tumbleweed",
            "full_product_name": {
              "text": "openSUSE Tumbleweed",
              "product_id": "openSUSE Tumbleweed",
              "cpe": "cpe:/o:opensuse:tumbleweed"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.11.10-5.1",
        "full_product_name": {
          "text": "python-Django-1.11.10-5.1",
          "product_id": "python-Django-1.11.10-5.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.11.15-2.1",
        "full_product_name": {
          "text": "python-Django-1.11.15-2.1",
          "product_id": "python-Django-1.11.15-2.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.8.19-3.4.1",
        "full_product_name": {
          "text": "python-Django-1.8.19-3.4.1",
          "product_id": "python-Django-1.8.19-3.4.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.8.19-3.6.1",
        "full_product_name": {
          "text": "python-Django-1.8.19-3.6.1",
          "product_id": "python-Django-1.8.19-3.6.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python36-Django-3.2.7-2.3",
        "full_product_name": {
          "text": "python36-Django-3.2.7-2.3",
          "product_id": "python36-Django-3.2.7-2.3"
        }
      },
      {
        "type": "Product Version",
        "name": "python38-Django-3.2.7-2.3",
        "full_product_name": {
          "text": "python38-Django-3.2.7-2.3",
          "product_id": "python38-Django-3.2.7-2.3"
        }
      },
      {
        "type": "Product Version",
        "name": "python39-Django-3.2.7-2.3",
        "full_product_name": {
          "text": "python39-Django-3.2.7-2.3",
          "product_id": "python39-Django-3.2.7-2.3"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "python-Django-1.8.19-3.6.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE OpenStack Cloud 6"
      },
      {
        "product_reference": "python-Django-1.8.19-3.4.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE OpenStack Cloud 7"
      },
      {
        "product_reference": "python-Django-1.11.10-5.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE Package Hub 12"
      },
      {
        "product_reference": "python-Django-1.11.15-2.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE Package Hub 12 SP1"
      },
      {
        "product_reference": "python36-Django-3.2.7-2.3",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python38-Django-3.2.7-2.3",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      },
      {
        "product_reference": "python39-Django-3.2.7-2.3",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "openSUSE Tumbleweed"
      }
    ]
  },
  "vulnerability": [
    {
      "notes": [
        {
          "text": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
          "title": "Vulnerability Description",
          "type": "General"
        }
      ],
      "cve": "CVE-2017-7233",
      "product_statuses": [
        {
          "type": "Fixed",
          "product_id": [
            "SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
            "SUSE OpenStack Cloud 7:python-Django-1.8.19-3.4.1",
            "SUSE Package Hub 12:python-Django-1.11.10-5.1",
            "SUSE Package Hub 12 SP1:python-Django-1.11.15-2.1",
            "openSUSE Tumbleweed:python36-Django-3.2.7-2.3",
            "openSUSE Tumbleweed:python38-Django-3.2.7-2.3",
            "openSUSE Tumbleweed:python39-Django-3.2.7-2.3"
          ]
        }
      ],
      "threats": [
        {
          "type": "Impact",
          "description": "low"
        }
      ],
      "cvss_score_sets": {
        "score_set_v_2": {
          "base_score_v_2": "4",
          "vector_v_2": "AV:N/AC:H/Au:N/C:P/I:P/A:N"
        },
        "score_set_v_3": {
          "base_score_v_3": "6.1",
          "vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N"
        }
      }
    }
  ]
}
