{
	"document_title": "CVE-2015-5144",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2015-5144"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "12",
				"date": "2023-02-11T02:30:11Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:31:36Z",
		"current_release_date": "2023-02-11T02:30:11Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2015-5144",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-October/001643.html",
			"description": "E-Mail link for SUSE-SU-2015:1810-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-October/001644.html",
			"description": "E-Mail link for SUSE-SU-2015:1815-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2016-January/001786.html",
			"description": "E-Mail link for SUSE-SU-2016:0044-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2015-10/msg00043.html",
			"description": "E-Mail link for openSUSE-SU-2015:1802-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2015-10/msg00046.html",
			"description": "E-Mail link for openSUSE-SU-2015:1813-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 1.0",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 1.0",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 1.0",
							"product_id": "SUSE Enterprise Storage 1.0",
							"cpe": "cpe:/o:suse:ses:1.0"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 2",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 2",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 2",
							"product_id": "SUSE Enterprise Storage 2",
							"cpe": "cpe:/o:suse:ses:2"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 5",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 5",
							"product_id": "SUSE OpenStack Cloud 5",
							"cpe": "cpe:/o:suse:cloud:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-10.2",
				"full_product_name": {
					"text": "python-Django-1.6.11-10.2",
					"product_id": "python-Django-1.6.11-10.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-3.1",
				"full_product_name": {
					"text": "python-Django-1.6.11-3.1",
					"product_id": "python-Django-1.6.11-3.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-8.1",
				"full_product_name": {
					"text": "python-Django-1.6.11-8.1",
					"product_id": "python-Django-1.6.11-8.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Django-1.6.11-8.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 1.0"
			},
			{
				"product_reference": "python-Django-1.6.11-3.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 2"
			},
			{
				"product_reference": "python-Django-1.6.11-10.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 5"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "Django before 1.4.21, 1.5.x through 1.6.x, 1.7.x before 1.7.9, and 1.8.x before 1.8.3 uses an incorrect regular expression, which allows remote attackers to inject arbitrary headers and conduct HTTP response splitting attacks via a newline character in an (1) email message to the EmailValidator, a (2) URL to the URLValidator, or unspecified vectors to the (3) validate_ipv4_address or (4) validate_slug validator.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2015-5144",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 1.0:python-Django-1.6.11-8.1",
						"SUSE Enterprise Storage 2:python-Django-1.6.11-3.1",
						"SUSE OpenStack Cloud 5:python-Django-1.6.11-10.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "moderate"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {}
			}
		}
	]
}
