{
  "document_title": "CVE-2015-2317",
  "document_type": "SUSE CVE",
  "document_publisher": {
    "type": "Vendor",
    "contact_details": "security@suse.de",
    "issuing_authority": "SUSE Security Team"
  },
  "document_tracking": {
    "identification": {
      "id": "SUSE CVE-2015-2317"
    },
    "status": "Interim",
    "version": "1",
    "revision_history": {
      "revision": {
        "number": "13",
        "date": "2023-05-13T00:51:52Z",
        "description": "current"
      }
    },
    "initial_release_date": "2021-05-30T13:28:22Z",
    "current_release_date": "2023-05-13T00:51:52Z",
    "generator": {
      "engine": "cve-database/bin/generate-cvrf-cve.pl",
      "date": "2020-12-27T01:00:00Z"
    }
  },
  "document_notes": [
    {
      "text": "CVE-2015-2317",
      "title": "CVE",
      "type": "Summary"
    },
    {
      "text": "The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x, 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly validate URLs, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a control character in a URL, as demonstrated by a \\x08javascript: URL.",
      "title": "Mitre CVE Description",
      "type": "Description"
    },
    {
      "text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "title": "Terms of Use",
      "type": "Legal Disclaimer"
    }
  ],
  "document_references": [
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2015-April/001339.html",
      "description": "E-Mail link for SUSE-SU-2015:0694-1"
    },
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2015-April/001340.html",
      "description": "E-Mail link for SUSE-SU-2015:0695-1"
    },
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2015-June/001452.html",
      "description": "E-Mail link for SUSE-SU-2015:1109-1"
    },
    {
      "type": "Self",
      "url": "https://lists.suse.com/pipermail/sle-security-updates/2015-June/001453.html",
      "description": "E-Mail link for SUSE-SU-2015:1112-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2015-04/msg00001.html",
      "description": "E-Mail link for openSUSE-SU-2015:0643-1"
    },
    {
      "type": "Self",
      "url": "https://lists.opensuse.org/opensuse-updates/2015-09/msg00035.html",
      "description": "E-Mail link for openSUSE-SU-2015:1598-1"
    },
    {
      "type": "Self",
      "url": "https://www.suse.com/support/security/rating/",
      "description": "SUSE Security Ratings"
    }
  ],
  "product_tree": {
    "branch": [
      {
        "type": "Product Family",
        "name": "SUSE Enterprise Storage 1.0",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE Enterprise Storage 1.0",
            "full_product_name": {
              "text": "SUSE Enterprise Storage 1.0",
              "product_id": "SUSE Enterprise Storage 1.0",
              "cpe": "cpe:/o:suse:ses:1.0"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "SUSE OpenStack Cloud 4",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE OpenStack Cloud 4",
            "full_product_name": {
              "text": "SUSE OpenStack Cloud 4",
              "product_id": "SUSE OpenStack Cloud 4",
              "cpe": "cpe:/o:suse:cloud:4"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Family",
        "name": "SUSE OpenStack Cloud 5",
        "branch": [
          {
            "type": "Product Name",
            "name": "SUSE OpenStack Cloud 5",
            "full_product_name": {
              "text": "SUSE OpenStack Cloud 5",
              "product_id": "SUSE OpenStack Cloud 5",
              "cpe": "cpe:/o:suse:cloud:5"
            }
          }
        ],
        "full_product_name": {}
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.6.11-0.7.1",
        "full_product_name": {
          "text": "python-Django-1.6.11-0.7.1",
          "product_id": "python-Django-1.6.11-0.7.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python-Django-1.6.11-4.1",
        "full_product_name": {
          "text": "python-Django-1.6.11-4.1",
          "product_id": "python-Django-1.6.11-4.1"
        }
      },
      {
        "type": "Product Version",
        "name": "python-django-1.5.12-0.9.1",
        "full_product_name": {
          "text": "python-django-1.5.12-0.9.1",
          "product_id": "python-django-1.5.12-0.9.1"
        }
      }
    ],
    "relationship": [
      {
        "product_reference": "python-Django-1.6.11-4.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE Enterprise Storage 1.0"
      },
      {
        "product_reference": "python-django-1.5.12-0.9.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE OpenStack Cloud 4"
      },
      {
        "product_reference": "python-Django-1.6.11-0.7.1",
        "relation_type": "Default Component Of",
        "relates_to_product_reference": "SUSE OpenStack Cloud 5"
      }
    ]
  },
  "vulnerability": [
    {
      "notes": [
        {
          "text": "The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x, 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly validate URLs, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a control character in a URL, as demonstrated by a \\x08javascript: URL.",
          "title": "Vulnerability Description",
          "type": "General"
        }
      ],
      "cve": "CVE-2015-2317",
      "product_statuses": [
        {
          "type": "Fixed",
          "product_id": [
            "SUSE Enterprise Storage 1.0:python-Django-1.6.11-4.1",
            "SUSE OpenStack Cloud 4:python-django-1.5.12-0.9.1",
            "SUSE OpenStack Cloud 5:python-Django-1.6.11-0.7.1"
          ]
        }
      ],
      "threats": [
        {
          "type": "Impact",
          "description": "moderate"
        }
      ],
      "cvss_score_sets": {
        "score_set_v_2": {
          "base_score_v_2": "4.3",
          "vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
        },
        "score_set_v_3": {}
      }
    }
  ]
}
