{
	"document_title": "CVE-2016-2512",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2016-2512"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "13",
				"date": "2023-07-01T00:21:02Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-05-30T13:39:42Z",
		"current_release_date": "2023-07-01T00:21:02Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2016-2512",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-April/003965.html",
			"description": "E-Mail link for SUSE-SU-2018:1102-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004225.html",
			"description": "E-Mail link for SUSE-SU-2018:1828-1"
		},
		{
			"type": "Self",
			"url": "https://lists.suse.com/pipermail/sle-security-updates/2018-June/004226.html",
			"description": "E-Mail link for SUSE-SU-2018:1830-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00103.html",
			"description": "E-Mail link for openSUSE-SU-2018:0824-1"
		},
		{
			"type": "Self",
			"url": "https://lists.opensuse.org/opensuse-updates/2018-03/msg00105.html",
			"description": "E-Mail link for openSUSE-SU-2018:0826-1"
		},
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 4",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 4",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 4",
							"product_id": "SUSE Enterprise Storage 4",
							"cpe": "cpe:/o:suse:ses:4"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE Enterprise Storage 5",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE Enterprise Storage 5",
						"full_product_name": {
							"text": "SUSE Enterprise Storage 5",
							"product_id": "SUSE Enterprise Storage 5",
							"cpe": "cpe:/o:suse:ses:5"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "SUSE OpenStack Cloud 6",
				"branch": [
					{
						"type": "Product Name",
						"name": "SUSE OpenStack Cloud 6",
						"full_product_name": {
							"text": "SUSE OpenStack Cloud 6",
							"product_id": "SUSE OpenStack Cloud 6",
							"cpe": "cpe:/o:suse:suse-openstack-cloud:6"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-5.5.1",
				"full_product_name": {
					"text": "python-Django-1.6.11-5.5.1",
					"product_id": "python-Django-1.6.11-5.5.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.6.11-6.5.1",
				"full_product_name": {
					"text": "python-Django-1.6.11-6.5.1",
					"product_id": "python-Django-1.6.11-6.5.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python-Django-1.8.19-3.6.1",
				"full_product_name": {
					"text": "python-Django-1.8.19-3.6.1",
					"product_id": "python-Django-1.8.19-3.6.1"
				}
			},
			{
				"type": "Product Version",
				"name": "python3-Django-1.10.4-1.1",
				"full_product_name": {
					"text": "python3-Django-1.10.4-1.1",
					"product_id": "python3-Django-1.10.4-1.1"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python-Django-1.6.11-5.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 4"
			},
			{
				"product_reference": "python-Django-1.6.11-6.5.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			},
			{
				"product_reference": "python-Django-1.8.19-3.6.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "SUSE OpenStack Cloud 6"
			},
			{
				"product_reference": "python3-Django-1.10.4-1.1",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "The utils.http.is_safe_url function in Django before 1.8.10 and 1.9.x before 1.9.3 allows remote attackers to redirect users to arbitrary web sites and conduct phishing attacks or possibly conduct cross-site scripting (XSS) attacks via a URL containing basic authentication, as demonstrated by http://mysite.example.com\\@attacker.com.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2016-2512",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"SUSE Enterprise Storage 4:python-Django-1.6.11-5.5.1",
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.5.1",
						"SUSE OpenStack Cloud 6:python-Django-1.8.19-3.6.1",
						"openSUSE Tumbleweed:python3-Django-1.10.4-1.1"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "4.3",
					"vector_v_2": "AV:N/AC:M/Au:N/C:N/I:P/A:N"
				},
				"score_set_v_3": {
					"base_score_v_3": "7.4",
					"vector_v_3": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:N/I:H/A:N"
				}
			}
		}
	]
}
