{
	"document_title": "CVE-2020-17446",
	"document_type": "SUSE CVE",
	"document_publisher": {
		"type": "Vendor",
		"contact_details": "security@suse.de",
		"issuing_authority": "SUSE Security Team"
	},
	"document_tracking": {
		"identification": {
			"id": "SUSE CVE-2020-17446"
		},
		"status": "Interim",
		"version": "1",
		"revision_history": {
			"revision": {
				"number": "3",
				"date": "2024-07-13T00:06:12Z",
				"description": "current"
			}
		},
		"initial_release_date": "2021-09-30T01:30:55Z",
		"current_release_date": "2024-07-13T00:06:12Z",
		"generator": {
			"engine": "cve-database/bin/generate-cvrf-cve.pl",
			"date": "2020-12-27T01:00:00Z"
		}
	},
	"document_notes": [
		{
			"text": "CVE-2020-17446",
			"title": "CVE",
			"type": "Summary"
		},
		{
			"text": "asyncpg before 0.21.0 allows a malicious PostgreSQL server to trigger a crash or execute arbitrary code (on a database client) via a crafted server response, because of access to an uninitialized pointer in the array data decoder.",
			"title": "Mitre CVE Description",
			"type": "Description"
		},
		{
			"text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
			"title": "Terms of Use",
			"type": "Legal Disclaimer"
		}
	],
	"document_references": [
		{
			"type": "Self",
			"url": "https://www.suse.com/support/security/rating/",
			"description": "SUSE Security Ratings"
		}
	],
	"product_tree": {
		"branch": [
			{
				"type": "Product Family",
				"name": "openSUSE Tumbleweed",
				"branch": [
					{
						"type": "Product Name",
						"name": "openSUSE Tumbleweed",
						"full_product_name": {
							"text": "openSUSE Tumbleweed",
							"product_id": "openSUSE Tumbleweed",
							"cpe": "cpe:/o:opensuse:tumbleweed"
						}
					}
				],
				"full_product_name": {}
			},
			{
				"type": "Product Version",
				"name": "python310-asyncpg-0.29.0-1.3",
				"full_product_name": {
					"text": "python310-asyncpg-0.29.0-1.3",
					"product_id": "python310-asyncpg-0.29.0-1.3"
				}
			},
			{
				"type": "Product Version",
				"name": "python311-asyncpg-0.29.0-1.3",
				"full_product_name": {
					"text": "python311-asyncpg-0.29.0-1.3",
					"product_id": "python311-asyncpg-0.29.0-1.3"
				}
			},
			{
				"type": "Product Version",
				"name": "python312-asyncpg-0.29.0-1.3",
				"full_product_name": {
					"text": "python312-asyncpg-0.29.0-1.3",
					"product_id": "python312-asyncpg-0.29.0-1.3"
				}
			},
			{
				"type": "Product Version",
				"name": "python38-asyncpg-0.22.0-2.2",
				"full_product_name": {
					"text": "python38-asyncpg-0.22.0-2.2",
					"product_id": "python38-asyncpg-0.22.0-2.2"
				}
			},
			{
				"type": "Product Version",
				"name": "python39-asyncpg-0.22.0-2.2",
				"full_product_name": {
					"text": "python39-asyncpg-0.22.0-2.2",
					"product_id": "python39-asyncpg-0.22.0-2.2"
				}
			}
		],
		"relationship": [
			{
				"product_reference": "python310-asyncpg-0.29.0-1.3",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python311-asyncpg-0.29.0-1.3",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python312-asyncpg-0.29.0-1.3",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python38-asyncpg-0.22.0-2.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			},
			{
				"product_reference": "python39-asyncpg-0.22.0-2.2",
				"relation_type": "Default Component Of",
				"relates_to_product_reference": "openSUSE Tumbleweed"
			}
		]
	},
	"vulnerability": [
		{
			"notes": [
				{
					"text": "asyncpg before 0.21.0 allows a malicious PostgreSQL server to trigger a crash or execute arbitrary code (on a database client) via a crafted server response, because of access to an uninitialized pointer in the array data decoder.",
					"title": "Vulnerability Description",
					"type": "General"
				}
			],
			"cve": "CVE-2020-17446",
			"product_statuses": [
				{
					"type": "Fixed",
					"product_id": [
						"openSUSE Tumbleweed:python310-asyncpg-0.29.0-1.3",
						"openSUSE Tumbleweed:python311-asyncpg-0.29.0-1.3",
						"openSUSE Tumbleweed:python312-asyncpg-0.29.0-1.3",
						"openSUSE Tumbleweed:python38-asyncpg-0.22.0-2.2",
						"openSUSE Tumbleweed:python39-asyncpg-0.22.0-2.2"
					]
				}
			],
			"threats": [
				{
					"type": "Impact",
					"description": "important"
				}
			],
			"cvss_score_sets": {
				"score_set_v_2": {
					"base_score_v_2": "7.5",
					"vector_v_2": "AV:N/AC:L/Au:N/C:P/I:P/A:P"
				},
				"score_set_v_3": {
					"base_score_v_3": "9.8",
					"vector_v_3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
				}
			}
		}
	]
}
